name: build

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          node-version: 16
      # Work around https://github.com/actions/checkout/issues/290
      - run: git fetch --force --tags

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install
      - run: mkdir artifacts
      - name: create tarball
        run: |
          GIT_DESCRIBE=$(git describe)
          sed -i -e "s/%GIT_DESCRIBE%/$(git describe)/g" ./public/index.html
          tar -czf artifacts/imbportal-${GIT_DESCRIBE}.tar.gz \
            --transform "s/^\./imbportal-${GIT_DESCRIBE}/" \
            --exclude=./artifacts \
            --exclude=./.git \
            .
      - uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: artifacts/imbportal-*.tar.gz
      # creating docker image and pushing to harbor
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/rcc-portals-a/apps-ipp:${{env.TAG}}
          #cache-from: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/rcc-portals-a/apps-ipp:cache
          #cache-to: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/rcc-portals-a/apps-ipp:cache,mode=max
#end

  deploy:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: dist
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*

